### ISSUE TITLE
New component (def ...) should be (defn ... [])

### ISSUE THREAD

**Issue by colliderwriter** [IB5k/component-schema-blog#1]
In database.clj and user.clj, the final forms are:

(def new-database (...))

and 

(def example-component (...))

Is there a reason those aren't (defn new-thing []) with parameter lists?

**Comment by pleasetrythisathome** [comment]
yes, the constructor like https://github.com/IB5k/component-schema-blog/blob/master/src/example/database.clj#L33 are created using middleware provided by ib5k.component.ctr `wrap-validation` https://github.com/IB5k/component-schema/blob/master/src/ib5k/component/ctr.cljc#L33 for example wraps the constructor function by validating the schema provided against passed in options before calling the constructor.

**Comment by colliderwriter** [comment]
Understood and closed
